############################ Default configuration #########################
baseURL = "https://boisterous-toffee-60cc83.netlify.app"
title = "SteavenGamerYT | Hream"
# theme
theme = "northendlab"
# post pagination
paginate = "10"
# post excerpt
summaryLength = "10"
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[markup.goldmark.renderer]
    unsafe = true
[markup.highlight]
      codeFences = true
      guessSyntax = true
      hl_Lines = ""
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = false
      tabWidth = 4
      noClasses = false

######################### Default Parameters ###########################
[params]
# logo
logo = "images/2897ec5d34936e14686134a874435197.jpg"
logoWidth = 121
logoHeight = 50
# favicon
favicon = "images/yma3c89hgvob1.jpg"
# meta data
author = "SteavenGamerYT"
description = "Having Fun with Technology"
# homepage main section
mainSections = ["posts"]
# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io
# copyright
copyright = ""
rssLimit = 20
# search *** true or false (if Search is disable Menu will align in Right) ***
search = true

header_search_layout = "expanded" # "expanded" or "popupable"
# Menu align *** "left", "right" or "center" (if Search is disable Menu will align in Right) ***
menu_align = "center"
# Blog-details page sidebar
sidebar = "right" # Sidebar value ("left", "right" or false)

code_copy_button = true # Turn on/off the code-copy-button for code-fields

######################## Site Variables #########################
[params.variables]
# Color Variables
primary_color = "#47c4f1"
secondary_color = "#9AC4F8"
text_color = "#666666"
text_color_dark = "#222222"
body_color = "#fff"
border_color = "#ACB9C4"
black = "#000"
white = "#fff"
light = "#F8F8F8"

# font variable
# Give your font name from google font. add font weight using ":wght@" and separate by ";"
# example: "Work Sans:wght@400;500;600"
primary_font = "PT Sans:wght@400;700"
secondary_font = ""
icon_font = "Font Awesome 5 Free"


######################## sidebar widgets #########################
[params.widgets]
sidebar = ["toc"]
# available widget : search,about-me,authors,categories,tags,recent-post,social,promotion,subscription

# preloader
[params.preloader]
enable = false
preloader = "" # use png, jpg, svg or gif format

# Subscription
[params.subscription]
enable = true
title = "Subscribe for our monthly newsletter."
input_placeholder = "Enter your email"

# cookies
[params.cookies]
enable = false
expire_days = 2

########################## Plugings ######################################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.min.css"
[[params.plugins.css]]
link = "css/custom-nav.css"


# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"
attributes = "crossorigin='anonymous' defer='defer' data-search-pseudo-elements"


############################## Social Site ##########################
[[params.social]]
icon = "fab fa-youtube" # Fontawesome icon pack https://fontawesome.com/icons
link = "https://youtube.com/steavengameryt1"
[[params.social]]
icon = "fab fa-github" # Fontawesome icon pack https://fontawesome.com/icons
link = "https://github.com/steavengameryt"
[[params.social]]
icon = "fas fa-rss" # Fontawesome icon pack https://fontawesome.com/icons
link = "https://boisterous-toffee-60cc83.netlify.app/rss/"

####################### Banner #######################################
[Languages.en]
[Languages.en.params]
    banner_bg_image = "images/bannerbackground.png"
    banner_title = "<strong>SteavenGamerYT</strong><br>How To Articles, <br>Image Downloads,<br> Tech Guides."
    banner_image = "images/operating systems.jpg"
    about_me_title = "SteavenGamerYT"
    about_me_bio = ""

[[params.social_profile]]
icon = "fab fa-github" # Fontawesome icon pack https://fontawesome.com/icons
link = "https://github.com/steavengameryt"
[[params.social_profile]]
icon = "fab fa-youtube" # Fontawesome icon pack https://fontawesome.com/icons
link = "https://youtube.com/steavengameryt1"

######################## call to action ###############################
[params.cta]
enable = false
image = "images/hugo-muscot.svg"
title = "Get the best hugo templates"
description = "Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus."

[params.cta.button]
enable = false
label = "Visit Here"
link = "https://gethugothemes.com/shop/"

############################# English - Main Menu ########################
[[Languages.en.menu.main]]
weight = 1
url = "/"
name = "Home"


[[Languages.en.menu.main]]
    name = "Latest Videos"
    url = "https://youtube.com/steavengameryt1/videos"
    parent = "Members"

[[Languages.en.menu.main]]
weight = 6
url = "#"
name = "Sections"
hasChildren = true
  
[[Languages.en.menu.main]]
    name = "Games"
    url = "/categories/games"
    parent = "Sections"

[[Languages.en.menu.main]]
    name = "Android"
    url = "/categories/android"
    parent = "Sections"

[[Languages.en.menu.main]]
    name = "Linux"
    url = "/categories/linux"
    parent = "Sections"

[[Languages.en.menu.main]]
    name = "MacOS"
    url = "/categories/macos"
    parent = "Sections"

[[Languages.en.menu.main]]
    name = "Windows"
    url = "/categories/windows"
    parent = "Sections"

############################# Footer Menu ########################

[[Languages.en.menu.footer]]
weight = 3
url = "privacy/"
name = "Privacy"

[[Languages.en.menu.footer]]
weight = 4
url = "terms-conditions/"
name = "Terms & Conditions"

[privacy]
  [privacy.googleAnalytics]
    disable = true